### ISSUE TITLE
Conflict resolution for multiple changed attributes on a single entity

### ISSUE THREAD

**Issue by mindreframer** [cachapa/sql_crdt#1] opened 2023-05-17 00:27 UTC
Thanks for this rather straightforward looking package! 

I have one question about following use case: 

entity: id, name, color, category
node1: ch1: changes color and name
node2: ch2: changes category and name

changes on node1 and node2 happen on the same state, means none of those changes is more "correct" than the other. 

ch2 arrives at server first, then ch1. Would it work in Last-Write-Wins fashion? Would it retain color and category changes without conflict?
How does the server decide, which change to apply first? 

Thanks!

**Comment by cachapa** [comment] 2023-05-17 07:15
The change with the highest HLC timestamp would win: HLCs are compared using date & time, followed by the vector counter, and finally the node id as a deterministic tie breaker.
So in a sense it is last-write-wins, except it's based on the timestamp rather than the first to arrive. The result of a merge is guaranteed to be the same regardless of order of operations.

In your example the result of the merge would cause either ch1 or ch2 to be lost since one record would "win" over the other.
This is by design as conflict resolution works on the record rather than its fields since data consistency cannot otherwise be guaranteed.

If you want to allow for simultaneous changes of properties, you have to mirror that in your data structure. Something like:
entity: id, name, color, category
entity_color: id, color
entity_category: id, category

(Closing since this isn't an issue with the code, but feel free to continue commenting)

**Closed by cachapa** 2023-05-17 07:15 UTC

**Comment by mindreframer** [comment] 2023-05-17 09:49
@cachapa Thanks for the quick response! Good to have my hunch confirmed. Do you plan to add some dev guides later? The code is quite clean and mostly self-explanatory, but to have some high-level docs would be great.

I might try to re-implement this package in TypeScript and Elixir, and an overview of taken trade-offs and gotchas would help. 

Have a great day!
Roman

**Comment by cachapa** [comment] 2023-05-17 10:02
Thanks!
I've been meaning to write _something_ on this, but whenever I start I always struggle to find the right audience: should I get really technical, or go more high-level?
I'm usually more comfortable answering direct questions, such as this one :-)

For now I have "living documentation" in the form of an end-to-end open source project: [tudo](https://github.com/cachapa/tudo).

A re-implementation in other languages could be really interesting, please keep me posted if you go ahead with it.
Funny thing, a couple of years ago @fum36205 and I built a prototype of sql_crdt for [StoryArk](https://storyark.eu/), and his backend implementation was in Elixir.

**Comment by mindreframer** [comment] 2023-05-17 10:06
@cachapa That's funny! :) Yeah, I'll try to orient myself on the "living documentation" and see how far I come. When I have something more concrete, I'll send you a link to the repo. 

If some questions come up, I'll post them here as issues, I hope that's ok. 

Thanks again!

**Comment by mindreframer** [comment] 2023-05-17 10:17
Docs: I guess it might make sense to start with technical details, since your audience might be more of the "local-first" crowd, and they already know the nice high level properties of CRDTs and sync issues in client / server architectures. Maybe a discord group with https://www.linen.dev/  to expose discussions for accessibility and SEO, if community-building and feedback is something you would like to facilitate. But just for docs I would keep it low-tech, couple markdown files in `guides/` folder with some mostly-unstructured brain-dumps would be already great. 

The maintainer of Replicache @aboodman has a couple public documents like following:  
- https://roamresearch.com/#/app/aboodman/search
- https://roamresearch.com/#/app/aboodman/page/p-fk069VQ
- https://replicache.notion.site/Diff-Strategies-3cccf424123042ed8796cf0773cacf4e
- https://replicache.notion.site/The-Row-Version-Strategy-5c5560b0ba3c437fae6eb34318b54712

They are not final and polished, but already helpful to understand trade-offs.

**Comment by cachapa** [comment] 2023-05-17 10:58
Thanks for the links, I'll have a look.

I'm honestly not too crazy on the idea of building a community since I already have more projects than there are hours in the day, and I try to keep my time commitments to a minimum, esp. when it involves other people.

I do think technical documentation and/or a guide makes sense. I'll have to consider the best way to create and host one.
For now I activated the Discussions tab in this repository, it may be a better way to have these sorts of interactions than (mis)using the issues :-)

**Comment by mindreframer** [comment] 2023-05-17 13:25
Community building: I can totally understand :) Thumbs up on the Discussions tab.
